blocks:
  - key: "input"
    type: "scoutos_input"
    depends:
      - type: "str"
        path: "name"
        default_value: "You"
  - key: "template"
    type: "scoutos_template"
    template: "Hello, {{name}}!"
    depends:
      - type: "str"
        path: "input.name"
  - key: "output"
    type: "scoutos_output"
    depends:
      - type: "str"
        path: "template.result"
