name: Publish Prerelease
on:
  push:
  workflow_run:
    workflows: ["checks"]
    types:
      - completed
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Run dependent job
      run: echo "This runs only if the Primary Workflow was successful."

