name: Publish Prerelease
on:
  push:
  workflow_run:
    workflows: ["checks"]
    types:
      - completed
    branches:
      - main
jobs:
  main:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
          python-version-file: '.python-version'

      - name: Update package version
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          NEW_VERSION=$(poetry version prerelease | awk '{print $2}').dev${COMMIT_SHA}
          echo "New version: $NEW_VERSION"
          poetry version $NEW_VERSION

      - name: Build
        run: poetry build

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish
